title: Lindy Collection
author: Tully
email: lindycollectionsite@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  A site collecting great content from the Lindy Hop Community.
  Including vintage clips, routines, solo jazz moves, and aerials.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.lindycollection.com"
# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github:
  url_base: https://github.com
  repository: lindycollection/www.lindycollection.com
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer
social:
  name: Lindy Collection
  links:
    - https://github.com/lindycollection

google_tag_manager: GTM-5SHPSFL

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
# highlighter: pygments # rouge # or pygments or null
# theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - scripts
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


video_width: 720
video_height: 560


collections:
  aerials:
    output: true
  clips:
  jazz:
    output: true
  historical_clips:
    output: true
  routines:
    output: true